//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 Intel(R).

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuoteAttestation) DeepCopyInto(out *QuoteAttestation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuoteAttestation.
func (in *QuoteAttestation) DeepCopy() *QuoteAttestation {
	if in == nil {
		return nil
	}
	out := new(QuoteAttestation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuoteAttestation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuoteAttestationCondition) DeepCopyInto(out *QuoteAttestationCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuoteAttestationCondition.
func (in *QuoteAttestationCondition) DeepCopy() *QuoteAttestationCondition {
	if in == nil {
		return nil
	}
	out := new(QuoteAttestationCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuoteAttestationList) DeepCopyInto(out *QuoteAttestationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuoteAttestation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuoteAttestationList.
func (in *QuoteAttestationList) DeepCopy() *QuoteAttestationList {
	if in == nil {
		return nil
	}
	out := new(QuoteAttestationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuoteAttestationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuoteAttestationSpec) DeepCopyInto(out *QuoteAttestationSpec) {
	*out = *in
	if in.Quote != nil {
		in, out := &in.Quote, &out.Quote
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Nonce != nil {
		in, out := &in.Nonce, &out.Nonce
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuoteAttestationSpec.
func (in *QuoteAttestationSpec) DeepCopy() *QuoteAttestationSpec {
	if in == nil {
		return nil
	}
	out := new(QuoteAttestationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuoteAttestationStatus) DeepCopyInto(out *QuoteAttestationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]QuoteAttestationCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuoteAttestationStatus.
func (in *QuoteAttestationStatus) DeepCopy() *QuoteAttestationStatus {
	if in == nil {
		return nil
	}
	out := new(QuoteAttestationStatus)
	in.DeepCopyInto(out)
	return out
}
