name: CI-2

on:
  push:
    branches: [ main, 'release-*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  use-info-from-previous-job:
    uses: ./.github/workflows/ghcr-io.yaml
    secrets: inherit
  
  push-to-Dockerhub-registry:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write

    steps:
    - name: Login to DockerHub container registry
      uses: docker/login-action@v2
      with:
        username: text
        password: text
      
    - name: Prepare Images
      id: images
      run: |
          DOCKER_IMAGE=docker.io/${IMG_NAME}:${IMG_TAG}
          GHCR_IMAGE=ghcr.io/${IMG_NAME}:${IMG_TAG}
          echo ::set-output name=dockerhub::${DOCKER_IMAGE}
          echo ::set-output name=ghcr::${GHCR_IMAGE}
    - name: Extract metadata (tags, labels) for Docker
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: |
            ${{ steps.images.outputs.dockerhub }}
            ${{ steps.images.outputs.ghcr}}
        tags: |
          type=ref,event=branch
          
    - name: Push to DockerHub Container Registry
      run: make docker-push
      env:
        REGISTRY: docker.io
        IMG_TAG: ${{ env.IMG_TAG }}
        IMG: ${{ steps.images.outputs.dockerhub }}
